### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by asilluron** [ng-al/apLamb#1]

**Comment by alvin-pivowar** [comment]
The unit tests are in github.com/alvin-pivowar/LambDevelopmentSandbox

**Comment by asilluron** [comment]
Sorry, I looked as hard as I could. I cannot find the tests.

Could you include the direct link?

**Comment by ng-al** [comment]
Andrew,

I apologize.  It looks like the tests were deleted when I updated the code on Dec 30.
I just looked at the "First Commit" commit, and the tests are in there (but deleted).
I will fix this tomorrow and send you the link.

-alvin

**Comment by asilluron** [comment]
Bumping.

**Comment by ng-al** [comment]
Tests have been restored in https://github.com/alvin-pivowar/LambDevelopmentSandbox.git
The tests can be found in /public/lib/apLamb

**Comment by asilluron** [comment]
I am re-opening the issue since my intention was to Fork this repo and commit changes. 

I am not sure what the procedure would be using tests from another repo?
